# Generated by Django 4.0.4 on 2022-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateTimeField(),
        ),
    ]
