# Generated by Django 4.0.4 on 2022-05-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rarev2api', '0002_alter_comment_created_on_alter_post_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
