# Generated by Django 4.0.4 on 2022-05-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0003_alter_rareuser_created_on_alter_rareuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rarev2api.post'),
        ),
    ]
