# Generated by Django 4.0.4 on 2022-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(),
        ),
    ]
