# Generated by Django 4.0.4 on 2022-05-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarev2api', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='postimages'),
        ),
    ]
